[package]
name = "risingwave-udaf-statistics"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]  # Required for WebAssembly compilation

[dependencies]
arrow-udf = "0.2"  # Provides macros and types for UDFs
